platform :ios, '13.0'
use_frameworks!

target 'PropertyInjector_Example' do
  pod 'PropertyInjector', :path => '../'

  target 'PropertyInjector_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 7.3'
    pod 'Nimble', '~> 13.0'
  end
end
